repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
          - --extend-exclude=venv
        language_version: python3.8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
        #- flake8-docstrings==1.5.0
        - pydocstyle==5.0.2
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1 
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/pylint
    rev: v2.15.4
    hooks:
      - id: pylint
        additional_dependencies:
        - aiohttp==3.7.3
        - netifaces==0.10.9
        - urllib3==1.26.3
        exclude: 'tests/'
        entry: env PYTHONPATH=. pylint
        args:
        - --ignore=setup.py
        - --extension-pkg-whitelist=netifaces
