image: python:3.8

definitions:
  steps:
    - step: &precommit-test
        name: Pre-Commit Test
        caches:
          - pip
        script:
          - pip install pre-commit
          - pre-commit run --all-files --verbose
    - step: &qa-test
        name: QA Test
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - pip install -r requirements-test.txt
          - black --check . pydaikin
          - flake8 . pydaikin
          - isort setup.py bin/pydaikin pydaikin/*.py
          - pylint --extension-pkg-whitelist=netifaces bin/pydaikin pydaikin/*.py

pipelines:
  default:
    - step: *precommit-test
    - step: *qa-test
  pull-requests:
    "**":
      - step: *precommit-test
      - step: *qa-test
          # We are not checking pylint strictly
          - pylint --fail-under=9.9 bin/pydaikin pydaikin
