image: python:3.11

definitions:
  steps:
    - step: &install-dependencies
        name: Install dependencies
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - pip install -r requirements-test.txt
    - step: &precommit-test
        name: Pre-Commit Test
        caches:
          - pip
        script:
          - pip install pre-commit
          - pre-commit run --all-files --verbose
    - step: &qa-test
        name: QA Test
        caches:
          - pip
        script:
          - black --check .
          - flake8 .
          - isort bin/*.py pydaikin/*.py
          - pylint --extension-pkg-whitelist=netifaces bin/*.py pydaikin/*.py
    - step: &unit-tests
        name: Unit Tests
        caches:
          - pip
        script:
          - python -m unittest

pipelines:
  default:
    - step: *install-dependencies
    - step: *unit-tests
    - step: *precommit-test
    - step: *qa-test
  pull-requests:
    '**':
      - step: *install-dependencies
      - step: *unit-tests
      - step: *precommit-test
      - step: *qa-test
