[tool.black]
skip-string-normalization = true
target-version = ["py311"]
include = '\.pyi?$|pydaikin$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
